name: quran
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  contained_tab_bar_view: ^0.8.0
  device_preview: ^1.2.0
  supabase_flutter: ^2.8.1
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  get_storage: ^2.1.1
  flutter_bloc: ^8.1.6
  lottie: ^3.2.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/png/
    - assets/json/
    - .env
    - assets/output/
